
package UI;

import java.sql.SQLException;

import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

import modelo.Alumno;
import modelo.Asignatura;
import modelo.Cursada;
import modelo.Modelo;

/**
 *
 * @author Leonel
 */
public class UI_Cursada_Altas extends javax.swing.JInternalFrame {
    Modelo modelo;
    private DefaultListModel listModel_total_alumnos = new DefaultListModel();
    private DefaultListModel listModel_alumnos_de_cursada = new DefaultListModel();
    private DefaultListModel listModel_cursadas = new DefaultListModel();
    private DefaultListModel listModel_asignaturas = new DefaultListModel();
    private Asignatura asignatura_en_uso = null;

    /** Creates new form Class1 */
    public UI_Cursada_Altas(Modelo modelo) {
        initComponents();
        this.modelo = modelo;
        this.jList_Total_Alumnos.setModel(listModel_total_alumnos);
        this.jList_Alumnos_Cursada.setModel(listModel_alumnos_de_cursada);
        this.jList_cursadas.setModel(listModel_cursadas);
        this.jList_asignaturas.setModel(listModel_asignaturas);
        this.actualizar_jList_total_alumnos();
        this.actualizar_jList_cursadas();
        this.actualizar_jList_asignaturas();
    }

    private void actualizar_jList_total_alumnos() {
        this.listModel_total_alumnos.clear();
        Iterator iterator_alumnos = modelo.getAlumnos()
                                          .values()
                                          .iterator();
        //Recorrer el contenido del Iterator
        while (iterator_alumnos.hasNext()) {
            Alumno alumno = (Alumno) iterator_alumnos.next();
            this.listModel_total_alumnos.addElement(alumno);
        }
    }

    private void actualizar_jList_asignaturas() {
        listModel_asignaturas.clear();
        Iterator iterator_asignaturas = modelo.getAsignaturas()
                                              .values()
                                              .iterator();
        //Recorrer el contenido del Iterator
        while (iterator_asignaturas.hasNext()) {
            Asignatura as = (Asignatura) iterator_asignaturas.next();
            listModel_asignaturas.addElement(as);
        }
    }

    private void actualizar_jList_cursadas() {
        this.listModel_cursadas.clear();
        if (this.asignatura_en_uso != null) {
            ArrayList<Cursada> cursadas_actuales = this.asignatura_en_uso.getCursadas();
            for (int i = 0; i < cursadas_actuales.size(); i++) {
                this.listModel_cursadas.addElement(cursadas_actuales.get(i));
            }
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents()//GEN-BEGIN:initComponents
    {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jText_Asignatura = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jText_Anio = new javax.swing.JTextField();
        jText_Cuatrimestre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList_Total_Alumnos = new javax.swing.JList();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList_cursadas = new javax.swing.JList();
        jButton_guardar_cursada = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jList_asignaturas = new javax.swing.JList();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList_Alumnos_Cursada = new javax.swing.JList();
        jButton_Agrega = new javax.swing.JButton();
        jButton_Quita = new javax.swing.JButton();

        setClosable(true);
        setTitle("Alta de Cursadas");
        setNormalBounds(new java.awt.Rectangle(0, 0, 950, 700));
        setPreferredSize(new java.awt.Dimension(950, 700));

        jLabel1.setText("Asig.:");

        jText_Asignatura.setEditable(false);
        jText_Asignatura.setFocusable(false);

        jLabel2.setText("Año:");

        jText_Anio.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jText_AnioActionPerformed(evt);
            }
        });
        jText_Anio.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                jText_KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt)
            {
                jText_KeyPressed(evt);
            }
        });

        jText_Cuatrimestre.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                jText_KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt)
            {
                jText_KeyPressed(evt);
            }
        });

        jLabel3.setText("Cuatr.:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jText_Anio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                    .addComponent(jText_Cuatrimestre)
                    .addComponent(jText_Asignatura))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jText_Asignatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jText_Anio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jText_Cuatrimestre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Listado total de Alumnos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 3, 18))); // NOI18N

        jScrollPane2.setViewportView(jList_Total_Alumnos);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Listado de Cursadas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 3, 18))); // NOI18N

        jList_cursadas.setModel(new javax.swing.AbstractListModel()
        {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList_cursadas.setEnabled(false);
        jList_cursadas.setFocusable(false);
        jScrollPane4.setViewportView(jList_cursadas);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE)
        );

        jButton_guardar_cursada.setText("Guardar nueva cursada");
        jButton_guardar_cursada.setEnabled(false);
        jButton_guardar_cursada.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton_guardar_cursadaActionPerformed(evt);
            }
        });

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Listado de Asignaturas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 3, 18))); // NOI18N

        jList_asignaturas.setModel(new javax.swing.AbstractListModel()
        {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList_asignaturas.addListSelectionListener(new javax.swing.event.ListSelectionListener()
        {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt)
            {
                jList_asignaturasValueChanged(evt);
            }
        });
        jScrollPane5.setViewportView(jList_asignaturas);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5)
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Alumnos en cursada", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 3, 18))); // NOI18N

        jScrollPane1.setViewportView(jList_Alumnos_Cursada);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jButton_Agrega.setText(">");
        jButton_Agrega.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton_AgregaActionPerformed(evt);
            }
        });

        jButton_Quita.setText("<");
        jButton_Quita.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton_QuitaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_Agrega)
                            .addComponent(jButton_Quita))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jButton_guardar_cursada))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(115, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jButton_Agrega)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_Quita))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_guardar_cursada))))
                .addContainerGap(120, Short.MAX_VALUE))
        );

        pack();
    }//GEN-END:initComponents

    private void jButton_guardar_cursadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_guardar_cursadaActionPerformed
        // TODO add your handling code here:

        Alumno al;

        int anio = Integer.parseInt(this.jText_Anio.getText());
        int cuatrimestre = Integer.parseInt(this.jText_Cuatrimestre.getText());
        ArrayList<Alumno> alumnos = new ArrayList<Alumno>();
        Cursada cursadaactual = new Cursada(anio, cuatrimestre);
        for (int i = 0; i < this.listModel_alumnos_de_cursada.size(); i++) {
            alumnos.add((Alumno) this.listModel_alumnos_de_cursada.get(i));
        }
        cursadaactual.setAlumnos(alumnos);
        cursadaactual.setAnio_fecha(anio);

        cursadaactual.setCuatrimestre(cuatrimestre);
        try {
            this.modelo
                .getModelo_abm_cursada()
                .AgregarCursada(this.asignatura_en_uso, cursadaactual);
            this.modelo.recuperarCursadas(this.asignatura_en_uso);
            this.actualizar_jList_total_alumnos();

            this.listModel_alumnos_de_cursada.removeAllElements();
            this.jText_Anio.setText("");
            this.jText_Asignatura.setText("");
            this.jText_Cuatrimestre.setText("");
            this.actualizar_jList_cursadas();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
       // this.jButton_Agrega.setEnabled(false);
    }//GEN-LAST:event_jButton_guardar_cursadaActionPerformed

    private void jButton_AgregaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton_AgregaActionPerformed
    {//GEN-HEADEREND:event_jButton_AgregaActionPerformed
        // TODO add your handling code here:
        List<Alumno> l = this.jList_Total_Alumnos.getSelectedValuesList();
        for (int i = 0; i < l.size(); i++) {
            this.listModel_alumnos_de_cursada.addElement(l.get(i));
            this.listModel_total_alumnos.removeElement(l.get(i));
        }
        this.verificaEnabled();
    }//GEN-LAST:event_jButton_AgregaActionPerformed

    private void jButton_QuitaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton_QuitaActionPerformed
    {//GEN-HEADEREND:event_jButton_QuitaActionPerformed
        // TODO add your handling code here:
        List<Alumno> l = this.jList_Alumnos_Cursada.getSelectedValuesList();
        for (int i = 0; i < l.size(); i++) {
            this.listModel_total_alumnos.addElement(l.get(i));
            this.listModel_alumnos_de_cursada.removeElement(l.get(i));

        }
        this.verificaEnabled();

    }//GEN-LAST:event_jButton_QuitaActionPerformed

    private void jText_KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jText_KeyPressed
        // TODO add your handling code here:
        this.verificaEnabled();
    }//GEN-LAST:event_jText_KeyPressed

    private void jText_AnioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText_AnioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jText_AnioActionPerformed

    private void jList_asignaturasValueChanged(javax.swing.event.ListSelectionEvent evt)//GEN-FIRST:event_jList_asignaturasValueChanged
    {//GEN-HEADEREND:event_jList_asignaturasValueChanged
    if (this.jList_asignaturas.getSelectedValue() != null) {
        this.asignatura_en_uso = (Asignatura) jList_asignaturas.getSelectedValue();
        this.jText_Asignatura.setText(this.asignatura_en_uso.toString());
        this.actualizar_jList_cursadas();


    }


    this.verificaEnabled();        
    
    }//GEN-LAST:event_jList_asignaturasValueChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Agrega;
    private javax.swing.JButton jButton_Quita;
    private javax.swing.JButton jButton_guardar_cursada;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList jList_Alumnos_Cursada;
    private javax.swing.JList jList_Total_Alumnos;
    private javax.swing.JList jList_asignaturas;
    private javax.swing.JList jList_cursadas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextField jText_Anio;
    private javax.swing.JTextField jText_Asignatura;
    private javax.swing.JTextField jText_Cuatrimestre;
    // End of variables declaration//GEN-END:variables
    private void verificaEnabled() {
        boolean no_son_null;
        boolean hay_textos;
        no_son_null = this.asignatura_en_uso != null && this.jList_Alumnos_Cursada
                                                            .getModel()
                                                            .getSize() > 0;
        try {
            Integer.parseInt(this.jText_Anio.getText());
            Integer.parseInt(this.jText_Cuatrimestre.getText());
            hay_textos = true;
        } catch (NumberFormatException e) {
            hay_textos = false;
        }
        this.jButton_guardar_cursada.setEnabled(no_son_null && hay_textos);
    }
}
