
package UI;

import arbol_visual.ArbolVisual;

import java.awt.Dimension;

import java.util.ArrayList;
import java.util.Iterator;

import javax.swing.DefaultListModel;
import javax.swing.tree.DefaultTreeModel;

import modelo.Asignatura;
import modelo.Cursada;
import modelo.Modelo;

/**
 *
 * @author guille
 */
public class UI_Parcial extends javax.swing.JInternalFrame
{
private Modelo modelo;
private Dimension dimensionPreferida=new Dimension(UI_Dimensiones.ANCHO_INTERNO,UI_Dimensiones.ALTO_INTERNO);
   private ArbolVisual jtree_arbol;
     
     private DefaultListModel listModel_cursadas = new DefaultListModel();
    private DefaultListModel listModel_asignaturas = new DefaultListModel();
     private Asignatura asignatura_en_uso=null;
     private Cursada cursada_en_curso=null;
    /** Creates new form UI_Parcial */
    public UI_Parcial(Modelo m)
    {
        this.setMinimumSize(new Dimension(UI_Dimensiones.ANCHO_INTERNO, UI_Dimensiones.ALTO_INTERNO));
        this.setMaximumSize(new Dimension(UI_Dimensiones.ANCHO_INTERNO, UI_Dimensiones.ALTO_INTERNO));
        this.setPreferredSize(new Dimension(UI_Dimensiones.ANCHO_INTERNO, UI_Dimensiones.ALTO_INTERNO));
        this.modelo=m;
        initComponents();
       this.jList_asignaturas.setModel(listModel_asignaturas);
       this.jList_cursadas.setModel(listModel_cursadas);
       this.actualizar_jList_asignaturas();
        this.jtree_arbol = (ArbolVisual) this.jScrollPane_jTreeVisual;
        
        this.jtree_arbol.setLineasRectas(true);
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents()//GEN-BEGIN:initComponents
    {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList_cursadas = new javax.swing.JList();
        jScrollPane_jTreeVisual = new ArbolVisual();
        jButton_guardar_ap = new javax.swing.JButton();
        jButton_eliminar_nodo = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList_asignaturas = new javax.swing.JList();
        jPanel15 = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        jText_Asignatura = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        jText_Anio = new javax.swing.JTextField();
        jText_Cuatrimestre = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jText_Nombre = new javax.swing.JTextField();

        setPreferredSize(this.dimensionPreferida);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Gestión de Parciales");

        jList_cursadas.setBorder(javax.swing.BorderFactory.createTitledBorder("Listado de Cursadas"));
        jList_cursadas.setModel(new javax.swing.AbstractListModel()
        {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList_cursadas.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jList_cursadasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList_cursadas);

        jScrollPane_jTreeVisual.setBorder(javax.swing.BorderFactory.createTitledBorder("Árbol Podado"));

        jButton_guardar_ap.setText("Guardar Parcial");
        jButton_guardar_ap.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jButton_guardar_apMouseClicked(evt);
            }
        });

        jButton_eliminar_nodo.setText("Eliminar Nodo");
        jButton_eliminar_nodo.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jButton_eliminar_nodoMouseClicked(evt);
            }
        });

        jList_asignaturas.setBorder(javax.swing.BorderFactory.createTitledBorder("Listado de Asignaturas"));
        jList_asignaturas.setModel(new javax.swing.AbstractListModel()
        {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList_asignaturas.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jList_asignaturasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jList_asignaturas);

        jLabel41.setText("Asig.:");

        jText_Asignatura.setEditable(false);
        jText_Asignatura.setFocusable(false);

        jLabel42.setText("Año:");

        jText_Anio.setFocusable(false);

        jText_Cuatrimestre.setFocusable(false);

        jLabel43.setText("Cuatr.:");

        jLabel44.setText("Nombre:");

        jText_Nombre.setEditable(false);
        jText_Nombre.setFocusable(false);

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel41)
                            .addComponent(jLabel42)
                            .addComponent(jLabel43))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jText_Asignatura, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                            .addComponent(jText_Anio)
                            .addComponent(jText_Cuatrimestre)))
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addComponent(jLabel44)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jText_Nombre)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel41)
                    .addComponent(jText_Asignatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel42)
                    .addComponent(jText_Anio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel43)
                    .addComponent(jText_Cuatrimestre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel44)
                    .addComponent(jText_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 6, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane_jTreeVisual, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_eliminar_nodo))
                    .addComponent(jButton_guardar_ap))
                .addContainerGap(99, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1)
                    .addContainerGap(895, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jScrollPane_jTreeVisual, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jButton_eliminar_nodo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_guardar_ap)
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }//GEN-END:initComponents

    private void jList_cursadasMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jList_cursadasMouseClicked
    {//GEN-HEADEREND:event_jList_cursadasMouseClicked
        //jList_asignaturasMouseClicked();
        
        if(this.jList_cursadas.getSelectedValue()!=null)
        {this.cursada_en_curso=(Cursada)this.jList_cursadas.getSelectedValue();
         this.jText_Anio.setText(String.valueOf(this.cursada_en_curso.getAnio_fecha()));
          this.jText_Cuatrimestre.setText(String.valueOf(this.cursada_en_curso.getCuatrimestre()));
          this.jText_Nombre.setText(String.valueOf(this.cursada_en_curso.getNombreCursada()));
            }
        
    }//GEN-LAST:event_jList_cursadasMouseClicked

    private void jButton_guardar_apMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jButton_guardar_apMouseClicked
    {//GEN-HEADEREND:event_jButton_guardar_apMouseClicked
        //bt_guardar_arbolActionPerformed();
    }//GEN-LAST:event_jButton_guardar_apMouseClicked

    private void jButton_eliminar_nodoMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jButton_eliminar_nodoMouseClicked
    {//GEN-HEADEREND:event_jButton_eliminar_nodoMouseClicked
        //jButton_eliminar_nodo();
    }//GEN-LAST:event_jButton_eliminar_nodoMouseClicked

    private void jList_asignaturasMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jList_asignaturasMouseClicked
    {//GEN-HEADEREND:event_jList_asignaturasMouseClicked
        // TODO add your handling code here:
        if(this.jList_asignaturas.getSelectedValue() != null)
        {
            this.asignatura_en_uso = (Asignatura) jList_asignaturas.getSelectedValue();
            this.jText_Asignatura.setText(this.asignatura_en_uso.toString());
            this.actualizar_jList_cursadas();
           DefaultTreeModel treeModelSeleccionado = this.asignatura_en_uso.getArbol_dominio().getTreeModel();

            jtree_arbol.setModel(treeModelSeleccionado);
        } 
    }//GEN-LAST:event_jList_asignaturasMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_eliminar_nodo;
    private javax.swing.JButton jButton_guardar_ap;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JList jList_asignaturas;
    private javax.swing.JList jList_cursadas;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane_jTreeVisual;
    private javax.swing.JTextField jText_Anio;
    private javax.swing.JTextField jText_Asignatura;
    private javax.swing.JTextField jText_Cuatrimestre;
    private javax.swing.JTextField jText_Nombre;
    // End of variables declaration//GEN-END:variables
    private void actualizar_jList_asignaturas()
    {
        listModel_asignaturas.clear();
        Iterator iterator_asignaturas = modelo.getAsignaturas().values().iterator();
        //Recorrer el contenido del Iterator
        while (iterator_asignaturas.hasNext())
        {
            Asignatura as = (Asignatura) iterator_asignaturas.next();
            listModel_asignaturas.addElement(as);
        }
    }
    
    private void actualizar_jList_cursadas()
    {
        this.listModel_cursadas.clear();
        if(this.asignatura_en_uso!=null)
        {
            ArrayList<Cursada> cursadas_actuales=this.asignatura_en_uso.getCursadas();  
            for(int i=0;i<cursadas_actuales.size();i++){
                this.listModel_cursadas.addElement(cursadas_actuales.get(i));
            }
        }
    }
}
