
package UI;

import arbol_visual.ArbolVisual;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

import modelo.Arbol_Perturbacion;


/**
 *
 * @author leonel
 */
public class UI_PanelAlta extends javax.swing.JPanel
{
    private UI_PanelArbol panel_arbol;
    private MouseAdapter mouseA = new MouseAdapter()
    {
        public void mouseClicked(MouseEvent me)
        {
            DefaultMutableTreeNode dmtn = panel_arbol.getNodo();
            if (dmtn != null)
            {
                jText_nodo_padre.setText(dmtn.toString());
            }
        }
    };

    /** Creates new form PanelAlta */
    public UI_PanelAlta()
    {
        initComponents();
        panel_arbol = new UI_PanelArbol();
        //panel_arbol.addMouseListener(mouseA);
        //this.jPanel_derecho.removeAll();
        //this.jPanel_derecho.setLayout(new BorderLayout());
        this.jScrollPane_JTreeVisual.setViewportView(panel_arbol);
        this.setVisible(true);
        this.habilitar_cargar_raiz();
    }
    
    public void setArbol_perturbacion(Arbol_Perturbacion arbol_perturbacion)
    {
        this.panel_arbol.setArbol_perturbacion(arbol_perturbacion);
    }

    public Arbol_Perturbacion getArbol_perturbacion()
    {
        return this.panel_arbol.getArbol_perturbacion();
    }
    
    public void setModel(DefaultTreeModel modeloArbol)
    {
        this.panel_arbol.setModel(modeloArbol);
    }
    
    public void crearRaiz()
    {
        this.panel_arbol.crearRaiz();
    }

    public void habilitar_cargar_raiz()
    {
        this.jText_nuevo_nodo.setEnabled(false);
        this.jLabel_nuevo_nodo.setEnabled(false);
        this.jLabel_padre.setText("RAIZ");
        this.jButton_agregar.setText("RAIZ");
    }

    public void habilitar_carga_nodos_nuevos()
    {
        this.jText_nuevo_nodo.setEnabled(true);
        this.jLabel_nuevo_nodo.setEnabled(true);
        this.jLabel_padre.setText("Nodo Padre:");
        this.jButton_agregar.setText("Agregar");
    }

    public void agregar_nodo()
    {
        if (!jText_nuevo_nodo.isEnabled())
        {
            this.habilitar_carga_nodos_nuevos();
            String raiz = jText_nodo_padre.getText().trim();
            this.panel_arbol.crearRaiz();
            panel_arbol.addMouseListener(mouseA);
        }
        else
        {
            String nombre = jText_nuevo_nodo.getText().trim();
            this.panel_arbol.agregar(nombre);
        }
    }

    public void cortar()
    {
        this.panel_arbol.borrar();
        this.jText_nodo_padre.setText("");
        this.jText_nuevo_nodo.setText("");
    }

    public void limpiar()
    {
        //this.panel_arbol.limpiar_panel();
        panel_arbol = null;
        panel_arbol = new UI_PanelArbol();
        //panel_arbol.addMouseListener(mouseA);
        //this.jPanel_derecho.removeAll();
        //this.jPanel_derecho.setLayout(new BorderLayout());
        this.jScrollPane_JTreeVisual.setViewportView(panel_arbol);
        this.setVisible(true);
        this.habilitar_cargar_raiz();
        this.jText_nodo_padre.setText("");
        this.jText_nuevo_nodo.setText("");
    }

    public void guardar()
    {

    }
    
    public void setJText_arbol(String nombre_arbol)
    {
        jTextField_arbol_seleccionado.setText(nombre_arbol);
    }
    
    public void setJText_descripcion(String descripcion)
    {
        jTextField_descripcion.setText(descripcion);
    }
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents()//GEN-BEGIN:initComponents
    {

        jPanel_nuevo_nodo = new javax.swing.JPanel();
        jLabel_padre = new javax.swing.JLabel();
        jLabel_nuevo_nodo = new javax.swing.JLabel();
        jText_nodo_padre = new javax.swing.JTextField();
        jText_nuevo_nodo = new javax.swing.JTextField();
        jButton_agregar = new javax.swing.JButton();
        jButton_limpiar = new javax.swing.JButton();
        jButton_cortar = new javax.swing.JButton();
        jScrollPane_JTreeVisual = new ArbolVisual();
        jPanel_arbol_seleccionado = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField_arbol_seleccionado = new javax.swing.JTextField();
        jTextField_descripcion = new javax.swing.JTextField();

        setMaximumSize(new java.awt.Dimension(660, 670));
        setMinimumSize(new java.awt.Dimension(660, 670));
        setName("Árbol de Dominio"); // NOI18N
        setPreferredSize(new java.awt.Dimension(660, 670));

        jPanel_nuevo_nodo.setPreferredSize(new java.awt.Dimension(200, 200));

        jLabel_padre.setText("Nodo Padre:");

        jLabel_nuevo_nodo.setText("Nuevo Nodo:");

        jButton_agregar.setText("Agregar");
        jButton_agregar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton_agregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_nuevo_nodoLayout = new javax.swing.GroupLayout(jPanel_nuevo_nodo);
        jPanel_nuevo_nodo.setLayout(jPanel_nuevo_nodoLayout);
        jPanel_nuevo_nodoLayout.setHorizontalGroup(
            jPanel_nuevo_nodoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_nuevo_nodoLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel_nuevo_nodoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_nuevo_nodoLayout.createSequentialGroup()
                        .addComponent(jLabel_nuevo_nodo)
                        .addGap(0, 0, 0)
                        .addComponent(jText_nuevo_nodo, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_agregar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_nuevo_nodoLayout.createSequentialGroup()
                        .addComponent(jLabel_padre)
                        .addGap(2, 2, 2)
                        .addComponent(jText_nodo_padre, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel_nuevo_nodoLayout.setVerticalGroup(
            jPanel_nuevo_nodoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_nuevo_nodoLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel_nuevo_nodoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jText_nodo_padre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_padre))
                .addGap(5, 5, 5)
                .addGroup(jPanel_nuevo_nodoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel_nuevo_nodo)
                    .addComponent(jText_nuevo_nodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_agregar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton_limpiar.setText("Limpiar");
        jButton_limpiar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton_limpiarActionPerformed(evt);
            }
        });

        jButton_cortar.setText("Cortar");
        jButton_cortar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton_cortarActionPerformed(evt);
            }
        });

        jPanel_arbol_seleccionado.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Árbol:");

        jLabel2.setText("Descripción:");

        jTextField_arbol_seleccionado.setEditable(false);
        jTextField_arbol_seleccionado.setBorder(null);

        jTextField_descripcion.setEditable(false);
        jTextField_descripcion.setBorder(null);

        javax.swing.GroupLayout jPanel_arbol_seleccionadoLayout = new javax.swing.GroupLayout(jPanel_arbol_seleccionado);
        jPanel_arbol_seleccionado.setLayout(jPanel_arbol_seleccionadoLayout);
        jPanel_arbol_seleccionadoLayout.setHorizontalGroup(
            jPanel_arbol_seleccionadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_arbol_seleccionadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_arbol_seleccionadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_arbol_seleccionadoLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(1, 1, 1)
                        .addComponent(jTextField_descripcion, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE))
                    .addGroup(jPanel_arbol_seleccionadoLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(4, 4, 4)
                        .addComponent(jTextField_arbol_seleccionado))))
        );
        jPanel_arbol_seleccionadoLayout.setVerticalGroup(
            jPanel_arbol_seleccionadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_arbol_seleccionadoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel_arbol_seleccionadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField_arbol_seleccionado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_arbol_seleccionadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane_JTreeVisual, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel_arbol_seleccionado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton_cortar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_limpiar))
                            .addComponent(jPanel_nuevo_nodo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel_arbol_seleccionado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel_nuevo_nodo, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(jScrollPane_JTreeVisual, javax.swing.GroupLayout.DEFAULT_SIZE, 569, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_limpiar)
                    .addComponent(jButton_cortar))
                .addGap(5, 5, 5))
        );
    }//GEN-END:initComponents

    private void jButton_agregarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton_agregarActionPerformed
    {//GEN-HEADEREND:event_jButton_agregarActionPerformed
        this.agregar_nodo();
    }//GEN-LAST:event_jButton_agregarActionPerformed

    private void jButton_cortarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton_cortarActionPerformed
    {//GEN-HEADEREND:event_jButton_cortarActionPerformed
        this.cortar();
    }//GEN-LAST:event_jButton_cortarActionPerformed

    private void jButton_limpiarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton_limpiarActionPerformed
    {//GEN-HEADEREND:event_jButton_limpiarActionPerformed
        this.limpiar();
    }//GEN-LAST:event_jButton_limpiarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_agregar;
    private javax.swing.JButton jButton_cortar;
    private javax.swing.JButton jButton_limpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_nuevo_nodo;
    private javax.swing.JLabel jLabel_padre;
    private javax.swing.JPanel jPanel_arbol_seleccionado;
    private javax.swing.JPanel jPanel_nuevo_nodo;
    private javax.swing.JScrollPane jScrollPane_JTreeVisual;
    private javax.swing.JTextField jTextField_arbol_seleccionado;
    private javax.swing.JTextField jTextField_descripcion;
    private javax.swing.JTextField jText_nodo_padre;
    private javax.swing.JTextField jText_nuevo_nodo;
    // End of variables declaration//GEN-END:variables

}
