
package UI;

import arbol_visual.ArbolVisual;

import java.util.ArrayList;
import java.util.Iterator;

import javax.swing.DefaultListModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

import modelo.Arbol_Perturbacion;
import modelo.Asignatura;
import modelo.Cursada;
import modelo.Modelo;
import modelo.Parcial;

/**
 *
 * @author guille
 */
public class UI_Parcial extends javax.swing.JInternalFrame {
    private Modelo modelo;
    private ArbolVisual jtree_arbol;
    private Arbol_Perturbacion arbolPodado;

    private DefaultListModel listModel_cursadas = new DefaultListModel();
    private DefaultListModel listModel_asignaturas = new DefaultListModel();
    private DefaultListModel listModel_parciales = new DefaultListModel();
    
    private Asignatura asignatura_en_uso = null;
    private Cursada cursada_en_uso = null;

    /** Creates new form UI_Parcial */
    public UI_Parcial(Modelo m) {
      
        this.modelo = m;
        initComponents();
        this.jList_asignaturas.setModel(listModel_asignaturas);
        this.jList_cursadas.setModel(listModel_cursadas);
            
            
        this.jList_parciales.setModel(listModel_parciales);
        this.actualizar_jList_asignaturas();
        this.jtree_arbol = (ArbolVisual) this.jScrollPane_jTreeVisual;

        this.jtree_arbol.setLineasRectas(true);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        jScrollPane_jTreeVisual = new ArbolVisual();
        jButton_guardar_ap = new javax.swing.JButton();
        jButton_eliminar_nodo = new javax.swing.JButton();
        jPanel15 = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        jText_Asignatura = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        jText_Nombre_Cursada = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        jText_Nombre = new javax.swing.JTextField();
        jButton_conservar_rama = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList_asignaturas = new javax.swing.JList();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList_cursadas = new javax.swing.JList();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList_parciales = new javax.swing.JList();

        setClosable(true);
        setTitle("Gestión de Parciales");
        setNormalBounds(new java.awt.Rectangle(0, 0, 950, 700));
        setPreferredSize(new java.awt.Dimension(950, 700));

        jScrollPane_jTreeVisual.setBorder(javax.swing.BorderFactory.createTitledBorder("Árbol Podado"));

        jButton_guardar_ap.setText("Guardar Parcial");
        jButton_guardar_ap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_guardar_apMouseClicked(evt);
            }
        });

        jButton_eliminar_nodo.setText("Eliminar Nodo");
        jButton_eliminar_nodo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_eliminar_nodoMouseClicked(evt);
            }
        });

        jLabel41.setText("Asig.:");

        jText_Asignatura.setEditable(false);
        jText_Asignatura.setFocusable(false);

        jLabel44.setText("Cursada:");

        jText_Nombre_Cursada.setEditable(false);
        jText_Nombre_Cursada.setFocusable(false);

        jLabel45.setText("Nombre:");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                        .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel44)
                            .addComponent(jLabel41))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addComponent(jLabel45)
                        .addGap(15, 15, 15)))
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jText_Nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addComponent(jText_Nombre_Cursada, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addComponent(jText_Asignatura, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel41)
                    .addComponent(jText_Asignatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel44)
                    .addComponent(jText_Nombre_Cursada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel45)
                    .addComponent(jText_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jButton_conservar_rama.setText("Conservar Rama");
        jButton_conservar_rama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_conservar_ramaActionPerformed(evt);
            }
        });

        jPanel1.setLayout(new java.awt.GridLayout());

        jList_asignaturas.setBorder(javax.swing.BorderFactory.createTitledBorder("Listado de Asignaturas"));
        jList_asignaturas.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList_asignaturas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList_asignaturasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jList_asignaturas);

        jPanel1.add(jScrollPane2);

        jList_cursadas.setBorder(javax.swing.BorderFactory.createTitledBorder("Listado de Cursadas"));
        jList_cursadas.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList_cursadas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList_cursadasMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jList_cursadas);

        jPanel1.add(jScrollPane3);

        jList_parciales.setBorder(javax.swing.BorderFactory.createTitledBorder("Listado de Parciales"));
        jList_parciales.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList_parciales.setFocusable(false);
        jList_parciales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList_parcialesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList_parciales);

        jPanel1.add(jScrollPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane_jTreeVisual, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jButton_eliminar_nodo, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_conservar_rama)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_guardar_ap)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane_jTreeVisual)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_guardar_ap)
                            .addComponent(jButton_eliminar_nodo)
                            .addComponent(jButton_conservar_rama))))
                .addContainerGap())
        );

        pack();
    }//GEN-END:initComponents

    private void jButton_guardar_apMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jButton_guardar_apMouseClicked
    {//GEN-HEADEREND:event_jButton_guardar_apMouseClicked
        this.modelo.getModelo_abm_parcial().AgregarParcial(this.cursada_en_uso,
                                                           new Parcial(0, this.jText_Nombre.getText(),
                                                                       this.arbolPodado));
        this.modelo.recuperarParciales(this.cursada_en_uso);
        limpiar();
      
    }//GEN-LAST:event_jButton_guardar_apMouseClicked

    private void jButton_eliminar_nodoMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jButton_eliminar_nodoMouseClicked
    {//GEN-HEADEREND:event_jButton_eliminar_nodoMouseClicked
        DefaultMutableTreeNode nodoSeleccionado = jtree_arbol.getNodoSeleccionado();
        DefaultTreeModel dtm = (DefaultTreeModel) this.jtree_arbol.getModel();
        if (nodoSeleccionado != null)
        {
            if (!nodoSeleccionado.isRoot())
            {
                dtm.removeNodeFromParent(nodoSeleccionado);
            } else
            {
                this.eliminar_arbol_completo();
            }
        }
    }//GEN-LAST:event_jButton_eliminar_nodoMouseClicked

    private void jButton_conservar_ramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_conservar_ramaActionPerformed
        /*
        DefaultMutableTreeNode nodoSeleccionado = jtree_arbol.getNodoSeleccionado();
        if (nodoSeleccionado != null)
        {
            DefaultTreeModel sub = new DefaultTreeModel(nodoSeleccionado,false);
            jtree_arbol.setModel(sub);
        }
      */  
    }//GEN-LAST:event_jButton_conservar_ramaActionPerformed

    private void jList_asignaturasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList_asignaturasMouseClicked
        // TODO add your handling code here:
        if (this.jList_asignaturas.getSelectedValue() != null)
        {
            this.asignatura_en_uso = (Asignatura) jList_asignaturas.getSelectedValue();
            this.jText_Asignatura.setText(this.asignatura_en_uso.toString());
            this.cursada_en_uso=null;
            this.actualizar_jList_cursadas();
            this.arbolPodado = Arbol_Perturbacion.deserializar(this.asignatura_en_uso.getArbol_dominio().serializar());
            jtree_arbol.setModel(this.arbolPodado.getTreeModel());
        }
        this.verificaEnabled();
    }//GEN-LAST:event_jList_asignaturasMouseClicked

    private void jList_cursadasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList_cursadasMouseClicked
        // TODO add your handling code here:
        if (this.jList_cursadas.getSelectedValue() != null)
        {
            this.cursada_en_uso = (Cursada) this.jList_cursadas.getSelectedValue();
            this.jText_Nombre_Cursada.setText(String.valueOf(this.cursada_en_uso.getNombreCursada()));
            this.actualizar_jList_parciales();
        }
        this.verificaEnabled();
    }//GEN-LAST:event_jList_cursadasMouseClicked

    private void jList_parcialesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList_parcialesMouseClicked
        //jList_asignaturasMouseClicked();
      
        

    }//GEN-LAST:event_jList_parcialesMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_conservar_rama;
    private javax.swing.JButton jButton_eliminar_nodo;
    private javax.swing.JButton jButton_guardar_ap;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JList jList_asignaturas;
    private javax.swing.JList jList_cursadas;
    private javax.swing.JList jList_parciales;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane_jTreeVisual;
    private javax.swing.JTextField jText_Asignatura;
    private javax.swing.JTextField jText_Nombre;
    private javax.swing.JTextField jText_Nombre_Cursada;
    // End of variables declaration//GEN-END:variables
    private void actualizar_jList_asignaturas() {
        listModel_asignaturas.clear();
        Iterator iterator_asignaturas = modelo.getAsignaturas().values().iterator();
        //Recorrer el contenido del Iterator
        while (iterator_asignaturas.hasNext())
        {
            Asignatura as = (Asignatura) iterator_asignaturas.next();
            listModel_asignaturas.addElement(as);
        }
    }

    private void actualizar_jList_cursadas() {
        this.listModel_cursadas.clear();
        if (this.asignatura_en_uso != null)
        {
            ArrayList<Cursada> cursadas_actuales = this.asignatura_en_uso.getCursadas();
            for (int i = 0; i < cursadas_actuales.size(); i++)
            {
                this.listModel_cursadas.addElement(cursadas_actuales.get(i));
            }
        }
    }
    
    private void actualizar_jList_parciales() {
        this.listModel_parciales.clear();
        if (this.cursada_en_uso != null)
        {
            ArrayList<Parcial> parciales_actuales = this.cursada_en_uso.getParciales();
            for (int i = 0; i < parciales_actuales.size(); i++)
            {
                this.listModel_parciales.addElement(parciales_actuales.get(i));
            }
        }
    }
    
    

    private void verificaEnabled() {
        boolean valida =
            (this.cursada_en_uso != null && this.asignatura_en_uso != null && this.jtree_arbol.getModel() != null);
        this.jButton_guardar_ap.setEnabled(valida);
    }

    private void eliminar_arbol_completo() {

        this.jtree_arbol.setModel(null);
        jtree_arbol.paintAll(this.jtree_arbol.getGraphics());

    }

    private void limpiar() {
        this.asignatura_en_uso = null;
        this.cursada_en_uso = null;
        this.jtree_arbol.setModel(null);
        this.jText_Asignatura.setText("");
        this.jText_Nombre.setText("");
        this.jText_Nombre_Cursada.setText("");
        this.actualizar_jList_cursadas();
        this.actualizar_jList_parciales();
        
        this.verificaEnabled();
        


    }

}
