
package UI;

import arbol_visual.ArbolVisual;

import java.awt.Dimension;

import java.util.ArrayList;
import java.util.Iterator;

import javax.swing.DefaultListModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

import modelo.Arbol_Perturbacion;
import modelo.Asignatura;
import modelo.Cursada;
import modelo.Modelo;
import modelo.Parcial;

/**
 *
 * @author guille
 */
public class UI_Parcial extends javax.swing.JInternalFrame {
    private Modelo modelo;
    private Dimension dimensionPreferida = new Dimension(UI_Dimensiones.ANCHO_INTERNO, UI_Dimensiones.ALTO_INTERNO);
    private ArbolVisual jtree_arbol;
    private Arbol_Perturbacion arbolPodado;

    private DefaultListModel listModel_cursadas = new DefaultListModel();
    private DefaultListModel listModel_asignaturas = new DefaultListModel();
    private Asignatura asignatura_en_uso = null;
    private Cursada cursada_en_curso = null;

    /** Creates new form UI_Parcial */
    public UI_Parcial(Modelo m) {
        this.setMinimumSize(new Dimension(UI_Dimensiones.ANCHO_INTERNO, UI_Dimensiones.ALTO_INTERNO));
        this.setMaximumSize(new Dimension(UI_Dimensiones.ANCHO_INTERNO, UI_Dimensiones.ALTO_INTERNO));
        this.setPreferredSize(new Dimension(UI_Dimensiones.ANCHO_INTERNO, UI_Dimensiones.ALTO_INTERNO));
        this.modelo = m;
        initComponents();
        this.jList_asignaturas.setModel(listModel_asignaturas);
        this.jList_cursadas.setModel(listModel_cursadas);
        this.actualizar_jList_asignaturas();
        this.jtree_arbol = (ArbolVisual) this.jScrollPane_jTreeVisual;

        this.jtree_arbol.setLineasRectas(true);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList_cursadas = new javax.swing.JList();
        jScrollPane_jTreeVisual = new ArbolVisual();
        jButton_guardar_ap = new javax.swing.JButton();
        jButton_eliminar_nodo = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList_asignaturas = new javax.swing.JList();
        jPanel15 = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        jText_Asignatura = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        jText_Nombre_Cursada = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        jText_Nombre = new javax.swing.JTextField();
        jButton_conservar_rama = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setPreferredSize(this.dimensionPreferida);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Gestión de Parciales");

        jList_cursadas.setBorder(javax.swing.BorderFactory.createTitledBorder("Listado de Cursadas"));
        jList_cursadas.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList_cursadas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList_cursadasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList_cursadas);

        jScrollPane_jTreeVisual.setBorder(javax.swing.BorderFactory.createTitledBorder("Árbol Podado"));

        jButton_guardar_ap.setText("Guardar Parcial");
        jButton_guardar_ap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_guardar_apMouseClicked(evt);
            }
        });

        jButton_eliminar_nodo.setText("Eliminar Nodo");
        jButton_eliminar_nodo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_eliminar_nodoMouseClicked(evt);
            }
        });

        jList_asignaturas.setBorder(javax.swing.BorderFactory.createTitledBorder("Listado de Asignaturas"));
        jList_asignaturas.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList_asignaturas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList_asignaturasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jList_asignaturas);

        jLabel41.setText("Asig.:");

        jText_Asignatura.setEditable(false);
        jText_Asignatura.setFocusable(false);

        jLabel44.setText("Cursada:");

        jText_Nombre_Cursada.setEditable(false);
        jText_Nombre_Cursada.setFocusable(false);

        jLabel45.setText("Nombre:");

        jText_Nombre.setEditable(false);

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel44)
                            .addComponent(jLabel41))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jText_Asignatura)
                            .addComponent(jText_Nombre_Cursada, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)))
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addComponent(jLabel45)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jText_Nombre)))
                .addContainerGap(165, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel41)
                    .addComponent(jText_Asignatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel44)
                    .addComponent(jText_Nombre_Cursada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel45)
                    .addComponent(jText_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jButton_conservar_rama.setText("Conservar Rama");
        jButton_conservar_rama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_conservar_ramaActionPerformed(evt);
            }
        });

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 17, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane_jTreeVisual, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButton_eliminar_nodo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton_conservar_rama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jButton1)))
                    .addComponent(jButton_guardar_ap))
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1)
                    .addContainerGap(851, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane_jTreeVisual, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(81, 81, 81)))
                        .addGap(8, 8, 8))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jButton_eliminar_nodo)
                        .addGap(16, 16, 16)
                        .addComponent(jButton_conservar_rama)
                        .addGap(36, 36, 36)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jButton_guardar_ap)
                .addContainerGap(49, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1)
                    .addContainerGap(621, Short.MAX_VALUE)))
        );

        pack();
    }//GEN-END:initComponents

    private void jList_cursadasMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jList_cursadasMouseClicked
    {//GEN-HEADEREND:event_jList_cursadasMouseClicked
        //jList_asignaturasMouseClicked();

        if (this.jList_cursadas.getSelectedValue() != null)
        {
            this.cursada_en_curso = (Cursada) this.jList_cursadas.getSelectedValue();
            this.jText_Nombre_Cursada.setText(String.valueOf(this.cursada_en_curso.getNombreCursada()));
        }
        this.verificaEnabled();
        
    }//GEN-LAST:event_jList_cursadasMouseClicked

    private void jButton_guardar_apMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jButton_guardar_apMouseClicked
    {//GEN-HEADEREND:event_jButton_guardar_apMouseClicked
      this.modelo.getModelo_abm_parcial().AgregarParcial(this.cursada_en_curso, new Parcial(0,this.jText_Nombre.getText(),this.arbolPodado));
      
    }//GEN-LAST:event_jButton_guardar_apMouseClicked

    private void jButton_eliminar_nodoMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jButton_eliminar_nodoMouseClicked
    {//GEN-HEADEREND:event_jButton_eliminar_nodoMouseClicked
        DefaultMutableTreeNode nodoSeleccionado = jtree_arbol.getNodoSeleccionado();
        DefaultTreeModel dtm = (DefaultTreeModel) this.jtree_arbol.getModel();
        if (nodoSeleccionado != null)
        {
            if (!nodoSeleccionado.isRoot())
            {
                dtm.removeNodeFromParent(nodoSeleccionado);
            } else
            {
                this.eliminar_arbol_completo();
            }
        }
    }//GEN-LAST:event_jButton_eliminar_nodoMouseClicked

    private void jList_asignaturasMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jList_asignaturasMouseClicked
    {//GEN-HEADEREND:event_jList_asignaturasMouseClicked
        // TODO add your handling code here:
        if (this.jList_asignaturas.getSelectedValue() != null)
        {

            this.asignatura_en_uso = (Asignatura) jList_asignaturas.getSelectedValue();
            this.jText_Asignatura.setText(this.asignatura_en_uso.toString());
            this.actualizar_jList_cursadas();
            this.arbolPodado = Arbol_Perturbacion.deserializar(this.asignatura_en_uso.getArbol_dominio().serializar());

            jtree_arbol.setModel(this.arbolPodado.getTreeModel());
        }
        this.verificaEnabled();
    }//GEN-LAST:event_jList_asignaturasMouseClicked

    private void jButton_conservar_ramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_conservar_ramaActionPerformed
       
        DefaultMutableTreeNode nodoSeleccionado = jtree_arbol.getNodoSeleccionado();
        if (nodoSeleccionado != null)
        {
            DefaultTreeModel sub = new DefaultTreeModel(nodoSeleccionado,false);
            jtree_arbol.setModel(sub);
        }
        
    }//GEN-LAST:event_jButton_conservar_ramaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.out.println(this.jtree_arbol.getNodoSeleccionado().getLevel());
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_conservar_rama;
    private javax.swing.JButton jButton_eliminar_nodo;
    private javax.swing.JButton jButton_guardar_ap;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JList jList_asignaturas;
    private javax.swing.JList jList_cursadas;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane_jTreeVisual;
    private javax.swing.JTextField jText_Asignatura;
    private javax.swing.JTextField jText_Nombre;
    private javax.swing.JTextField jText_Nombre_Cursada;
    // End of variables declaration//GEN-END:variables
    private void actualizar_jList_asignaturas() {
        listModel_asignaturas.clear();
        Iterator iterator_asignaturas = modelo.getAsignaturas().values().iterator();
        //Recorrer el contenido del Iterator
        while (iterator_asignaturas.hasNext())
        {
            Asignatura as = (Asignatura) iterator_asignaturas.next();
            listModel_asignaturas.addElement(as);
        }
    }

    private void actualizar_jList_cursadas() {
        this.listModel_cursadas.clear();
        if (this.asignatura_en_uso != null)
        {
            ArrayList<Cursada> cursadas_actuales = this.asignatura_en_uso.getCursadas();
            for (int i = 0; i < cursadas_actuales.size(); i++)
            {
                this.listModel_cursadas.addElement(cursadas_actuales.get(i));
            }
        }
    }

    private void verificaEnabled() {
        boolean valida =
            (this.cursada_en_curso != null && this.asignatura_en_uso != null && this.jtree_arbol.getModel() != null);
        this.jButton_guardar_ap.setEnabled(valida);
    }

    private void eliminar_arbol_completo() {

        this.jtree_arbol.setModel(null);
        jtree_arbol.paintAll(this.jtree_arbol.getGraphics());

    }

}
